version: '3'

services:
  webapp:
    build: ./webapp/
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app/
      - /app/node_modules
    env_file:
      - ./env_files/.postgres.env
    networks:
      - backend
      
  postgres:
    image: postgres:9.6
    container_name: postgres-db
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
    env_file:
      - ./env_files/.postgres.env
    networks:
      - backend
  
networks:
  backend:

volumes:
  postgres-data: